CREATE DATABASE IF NOT EXISTS `cupoftea_fsjs24v2` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;
USE `cupoftea_fsjs24v2`;

CREATE TABLE `CATEGORY` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(42),
  `description` VARCHAR(400),
  `url_img` VARCHAR(100),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `TEA_PACKAGING` (
  `tea_id` INT UNSIGNED NOT NULL,
  `packaging_id` INT UNSIGNED NOT NULL,
  `ref` VARCHAR(42),
  `price` SMALLINT UNSIGNED,
  PRIMARY KEY (`tea_id`, `packaging_id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
²
CREATE TABLE `PACKAGING` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `weight` VARCHAR(10),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `TEA` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mainTitle` VARCHAR(42),
  `subTitle` VARCHAR(42),
  `description` VARCHAR(400),
  `url_img` VARCHAR(100),
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `TEA_PACKAGING` ADD FOREIGN KEY (`tea_id`) REFERENCES `TEA` (`id`);
ALTER TABLE `TEA_PACKAGING` ADD FOREIGN KEY (`packaging_id`) REFERENCES `PACKAGING` (`id`);
ALTER TABLE `TEA` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORY` (`id`);
